#!/usr/bin/env cmd /c
@echo off

set ANDROID_NDK_RELEASE=android-ndk-r8e

rem set ANDROID_NDK_COMPILER_TYPE=clang
rem set ANDROID_NDK_COMPILER_VERSION=3.1
rem set ANDROID_NDK_COMPILER_TOOLCHAIN_FOR_TOOLCHAIN=clang
set ANDROID_NDK_COMPILER_TYPE=gcc
set ANDROID_NDK_COMPILER_VERSION=4.6
set ANDROID_NDK_COMPILER_TOOLCHAIN_FOR_TOOLCHAIN=

set ANDROID_NDK_TARGET=arm-linux-androideabi
set ANDROID_NDK_HOST=windows
set ANDROID_NDK_HOST_ARCH=x86
rem android-14 = android 4.0 ice cream sandwich
set API_LEVEL=android-14

set PATH_TO_BAT_DIRECTORY=%~dp0

set TOOLS_ANDROID=%PATH_TO_BAT_DIRECTORY%..
rem set TOOLS_ANDROID_CYGWIN="%TOOLS_ANDROID%/cygwin"
set TOOLS_ANDROID_CYGWIN=C:\cygwin
set ANDROID_NDK="%TOOLS_ANDROID%\%ANDROID_NDK_RELEASE%"
rem set ANDROID_NDK_COMPILER="%ANDROID_NDK%\toolchains\%ANDROID_NDK_COMPILER_TYPE%-%ANDROID_NDK_COMPILER_VERSION%\prebuilt\%ANDROID_NDK_HOST%\bin\"
set ANDROID_NDK_STANDALONE_COMPILER="%TOOLS_ANDROID%\compiler"


IF NOT EXIST ..\%ANDROID_NDK_RELEASE% (
	cmd /c "unzip.exe ..\%ANDROID_NDK_RELEASE%-%ANDROID_NDK_HOST%-%ANDROID_NDK_HOST_ARCH%.zip -d .."
)


%TOOLS_ANDROID_CYGWIN%\bin\bash.exe -c '$(cygpath -u %ANDROID_NDK%)/build/tools/make-standalone-toolchain.sh --platform=%API_LEVEL% --install-dir=$(cygpath -u %ANDROID_NDK_STANDALONE_COMPILER%) --toolchain=%ANDROID_NDK_TARGET%-%ANDROID_NDK_COMPILER_TYPE_FOR_TOOLCHAIN%%ANDROID_NDK_COMPILER_VERSION%'

rem set PATH=%ANDROID_NDK_STANDALONE_COMPILER%\bin;%PATH%

